// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/automosaic.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<DownloadEvent> dco_decode_StreamSink_download_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ProcessEvent> dco_decode_StreamSink_process_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ArchiveAnalyzeOptions dco_decode_archive_analyze_options(dynamic raw);

  @protected
  BackendInfo dco_decode_backend_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ArchiveAnalyzeOptions dco_decode_box_autoadd_archive_analyze_options(
    dynamic raw,
  );

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  PresetDetail dco_decode_box_autoadd_preset_detail(dynamic raw);

  @protected
  ProcessOptions dco_decode_box_autoadd_process_options(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  DownloadEvent dco_decode_download_event(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<BackendInfo> dco_decode_list_backend_info(dynamic raw);

  @protected
  List<ModelInfo> dco_decode_list_model_info(dynamic raw);

  @protected
  List<PresetInfo> dco_decode_list_preset_info(dynamic raw);

  @protected
  List<PreviewBox> dco_decode_list_preview_box(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReviewInstance> dco_decode_list_review_instance(dynamic raw);

  @protected
  ModelInfo dco_decode_model_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PresetDetail? dco_decode_opt_box_autoadd_preset_detail(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Float32List? dco_decode_opt_list_prim_f_32_strict(dynamic raw);

  @protected
  PresetDetail dco_decode_preset_detail(dynamic raw);

  @protected
  PresetInfo dco_decode_preset_info(dynamic raw);

  @protected
  PreviewBox dco_decode_preview_box(dynamic raw);

  @protected
  PreviewFrame dco_decode_preview_frame(dynamic raw);

  @protected
  ProcessEvent dco_decode_process_event(dynamic raw);

  @protected
  ProcessOptions dco_decode_process_options(dynamic raw);

  @protected
  ProcessStage dco_decode_process_stage(dynamic raw);

  @protected
  ReviewFrame dco_decode_review_frame(dynamic raw);

  @protected
  ReviewInstance dco_decode_review_instance(dynamic raw);

  @protected
  ReviewMeta dco_decode_review_meta(dynamic raw);

  @protected
  SamPromptResult dco_decode_sam_prompt_result(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VideoInfo dco_decode_video_info(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<DownloadEvent> sse_decode_StreamSink_download_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ProcessEvent> sse_decode_StreamSink_process_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ArchiveAnalyzeOptions sse_decode_archive_analyze_options(
    SseDeserializer deserializer,
  );

  @protected
  BackendInfo sse_decode_backend_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ArchiveAnalyzeOptions sse_decode_box_autoadd_archive_analyze_options(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PresetDetail sse_decode_box_autoadd_preset_detail(
    SseDeserializer deserializer,
  );

  @protected
  ProcessOptions sse_decode_box_autoadd_process_options(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  DownloadEvent sse_decode_download_event(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<BackendInfo> sse_decode_list_backend_info(SseDeserializer deserializer);

  @protected
  List<ModelInfo> sse_decode_list_model_info(SseDeserializer deserializer);

  @protected
  List<PresetInfo> sse_decode_list_preset_info(SseDeserializer deserializer);

  @protected
  List<PreviewBox> sse_decode_list_preview_box(SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReviewInstance> sse_decode_list_review_instance(
    SseDeserializer deserializer,
  );

  @protected
  ModelInfo sse_decode_model_info(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PresetDetail? sse_decode_opt_box_autoadd_preset_detail(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Float32List? sse_decode_opt_list_prim_f_32_strict(
    SseDeserializer deserializer,
  );

  @protected
  PresetDetail sse_decode_preset_detail(SseDeserializer deserializer);

  @protected
  PresetInfo sse_decode_preset_info(SseDeserializer deserializer);

  @protected
  PreviewBox sse_decode_preview_box(SseDeserializer deserializer);

  @protected
  PreviewFrame sse_decode_preview_frame(SseDeserializer deserializer);

  @protected
  ProcessEvent sse_decode_process_event(SseDeserializer deserializer);

  @protected
  ProcessOptions sse_decode_process_options(SseDeserializer deserializer);

  @protected
  ProcessStage sse_decode_process_stage(SseDeserializer deserializer);

  @protected
  ReviewFrame sse_decode_review_frame(SseDeserializer deserializer);

  @protected
  ReviewInstance sse_decode_review_instance(SseDeserializer deserializer);

  @protected
  ReviewMeta sse_decode_review_meta(SseDeserializer deserializer);

  @protected
  SamPromptResult sse_decode_sam_prompt_result(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VideoInfo sse_decode_video_info(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_download_event_Sse(
    RustStreamSink<DownloadEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_process_event_Sse(
    RustStreamSink<ProcessEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_archive_analyze_options(
    ArchiveAnalyzeOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_backend_info(BackendInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_archive_analyze_options(
    ArchiveAnalyzeOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_preset_detail(
    PresetDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_process_options(
    ProcessOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_download_event(DownloadEvent self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_backend_info(
    List<BackendInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_model_info(
    List<ModelInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_preset_info(
    List<PresetInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_preview_box(
    List<PreviewBox> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_review_instance(
    List<ReviewInstance> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_model_info(ModelInfo self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_preset_detail(
    PresetDetail? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_f_32_strict(
    Float32List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_preset_detail(PresetDetail self, SseSerializer serializer);

  @protected
  void sse_encode_preset_info(PresetInfo self, SseSerializer serializer);

  @protected
  void sse_encode_preview_box(PreviewBox self, SseSerializer serializer);

  @protected
  void sse_encode_preview_frame(PreviewFrame self, SseSerializer serializer);

  @protected
  void sse_encode_process_event(ProcessEvent self, SseSerializer serializer);

  @protected
  void sse_encode_process_options(
    ProcessOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_process_stage(ProcessStage self, SseSerializer serializer);

  @protected
  void sse_encode_review_frame(ReviewFrame self, SseSerializer serializer);

  @protected
  void sse_encode_review_instance(
    ReviewInstance self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_review_meta(ReviewMeta self, SseSerializer serializer);

  @protected
  void sse_encode_sam_prompt_result(
    SamPromptResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_video_info(VideoInfo self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
