// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/automosaic.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -722867295;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_automosaic_studio',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Stream<ProcessEvent> crateApiAutomosaicArchiveAnalyze({
    required String input,
    required String masksDir,
    required ArchiveAnalyzeOptions opts,
  });

  Stream<ProcessEvent> crateApiAutomosaicArchiveRender({
    required String input,
    required String masksDir,
    required String output,
    required String style,
    required int strength,
    required String hwaccel,
    required String encoder,
    required String bitrate,
  });

  Future<void> crateApiAutomosaicCancelProcess();

  Stream<DownloadEvent> crateApiAutomosaicDownloadModel({required String file});

  Future<List<BackendInfo>> crateApiAutomosaicListBackends();

  Future<List<ModelInfo>> crateApiAutomosaicListModels();

  Future<List<PresetInfo>> crateApiAutomosaicListPresets({
    required String device,
  });

  Future<PreviewFrame> crateApiAutomosaicPreviewFrame({
    required String input,
    required double positionSecs,
    required double conf,
    required String device,
    required String preset,
    required String style,
    required int strength,
  });

  Future<VideoInfo> crateApiAutomosaicProbeVideo({required String path});

  Stream<ProcessEvent> crateApiAutomosaicProcessVideo({
    required String input,
    required String output,
    required ProcessOptions opts,
  });

  Future<void> crateApiAutomosaicReviewClearFrame({
    required String masksDir,
    required BigInt frameIdx,
  });

  Future<ReviewFrame> crateApiAutomosaicReviewFrame({
    required String input,
    required String masksDir,
    required BigInt frameIdx,
  });

  Future<ReviewMeta> crateApiAutomosaicReviewMeta({
    required String input,
    required String masksDir,
  });

  Future<SamPromptResult> crateApiAutomosaicReviewSamPrompt({
    required String input,
    required BigInt frameIdx,
    required List<double> points,
    Float32List? box,
    required String samSize,
  });

  Future<void> crateApiAutomosaicReviewSaveBrush({
    required String masksDir,
    required BigInt frameIdx,
    required bool add,
    required List<int> mask,
  });

  Future<bool> crateApiAutomosaicVerifyModel({required String file});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<ProcessEvent> crateApiAutomosaicArchiveAnalyze({
    required String input,
    required String masksDir,
    required ArchiveAnalyzeOptions opts,
  }) {
    final sink = RustStreamSink<ProcessEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(input, serializer);
            sse_encode_String(masksDir, serializer);
            sse_encode_box_autoadd_archive_analyze_options(opts, serializer);
            sse_encode_StreamSink_process_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 1,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiAutomosaicArchiveAnalyzeConstMeta,
          argValues: [input, masksDir, opts, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiAutomosaicArchiveAnalyzeConstMeta =>
      const TaskConstMeta(
        debugName: "archive_analyze",
        argNames: ["input", "masksDir", "opts", "sink"],
      );

  @override
  Stream<ProcessEvent> crateApiAutomosaicArchiveRender({
    required String input,
    required String masksDir,
    required String output,
    required String style,
    required int strength,
    required String hwaccel,
    required String encoder,
    required String bitrate,
  }) {
    final sink = RustStreamSink<ProcessEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(input, serializer);
            sse_encode_String(masksDir, serializer);
            sse_encode_String(output, serializer);
            sse_encode_String(style, serializer);
            sse_encode_u_32(strength, serializer);
            sse_encode_String(hwaccel, serializer);
            sse_encode_String(encoder, serializer);
            sse_encode_String(bitrate, serializer);
            sse_encode_StreamSink_process_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 2,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiAutomosaicArchiveRenderConstMeta,
          argValues: [
            input,
            masksDir,
            output,
            style,
            strength,
            hwaccel,
            encoder,
            bitrate,
            sink,
          ],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiAutomosaicArchiveRenderConstMeta =>
      const TaskConstMeta(
        debugName: "archive_render",
        argNames: [
          "input",
          "masksDir",
          "output",
          "style",
          "strength",
          "hwaccel",
          "encoder",
          "bitrate",
          "sink",
        ],
      );

  @override
  Future<void> crateApiAutomosaicCancelProcess() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAutomosaicCancelProcessConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAutomosaicCancelProcessConstMeta =>
      const TaskConstMeta(debugName: "cancel_process", argNames: []);

  @override
  Stream<DownloadEvent> crateApiAutomosaicDownloadModel({
    required String file,
  }) {
    final sink = RustStreamSink<DownloadEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(file, serializer);
            sse_encode_StreamSink_download_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 4,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiAutomosaicDownloadModelConstMeta,
          argValues: [file, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiAutomosaicDownloadModelConstMeta =>
      const TaskConstMeta(
        debugName: "download_model",
        argNames: ["file", "sink"],
      );

  @override
  Future<List<BackendInfo>> crateApiAutomosaicListBackends() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_backend_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAutomosaicListBackendsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAutomosaicListBackendsConstMeta =>
      const TaskConstMeta(debugName: "list_backends", argNames: []);

  @override
  Future<List<ModelInfo>> crateApiAutomosaicListModels() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_model_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAutomosaicListModelsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAutomosaicListModelsConstMeta =>
      const TaskConstMeta(debugName: "list_models", argNames: []);

  @override
  Future<List<PresetInfo>> crateApiAutomosaicListPresets({
    required String device,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(device, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_preset_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAutomosaicListPresetsConstMeta,
        argValues: [device],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAutomosaicListPresetsConstMeta =>
      const TaskConstMeta(debugName: "list_presets", argNames: ["device"]);

  @override
  Future<PreviewFrame> crateApiAutomosaicPreviewFrame({
    required String input,
    required double positionSecs,
    required double conf,
    required String device,
    required String preset,
    required String style,
    required int strength,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          sse_encode_f_64(positionSecs, serializer);
          sse_encode_f_32(conf, serializer);
          sse_encode_String(device, serializer);
          sse_encode_String(preset, serializer);
          sse_encode_String(style, serializer);
          sse_encode_u_32(strength, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_preview_frame,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAutomosaicPreviewFrameConstMeta,
        argValues: [input, positionSecs, conf, device, preset, style, strength],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAutomosaicPreviewFrameConstMeta =>
      const TaskConstMeta(
        debugName: "preview_frame",
        argNames: [
          "input",
          "positionSecs",
          "conf",
          "device",
          "preset",
          "style",
          "strength",
        ],
      );

  @override
  Future<VideoInfo> crateApiAutomosaicProbeVideo({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAutomosaicProbeVideoConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAutomosaicProbeVideoConstMeta =>
      const TaskConstMeta(debugName: "probe_video", argNames: ["path"]);

  @override
  Stream<ProcessEvent> crateApiAutomosaicProcessVideo({
    required String input,
    required String output,
    required ProcessOptions opts,
  }) {
    final sink = RustStreamSink<ProcessEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(input, serializer);
            sse_encode_String(output, serializer);
            sse_encode_box_autoadd_process_options(opts, serializer);
            sse_encode_StreamSink_process_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 10,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiAutomosaicProcessVideoConstMeta,
          argValues: [input, output, opts, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiAutomosaicProcessVideoConstMeta =>
      const TaskConstMeta(
        debugName: "process_video",
        argNames: ["input", "output", "opts", "sink"],
      );

  @override
  Future<void> crateApiAutomosaicReviewClearFrame({
    required String masksDir,
    required BigInt frameIdx,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(masksDir, serializer);
          sse_encode_u_64(frameIdx, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAutomosaicReviewClearFrameConstMeta,
        argValues: [masksDir, frameIdx],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAutomosaicReviewClearFrameConstMeta =>
      const TaskConstMeta(
        debugName: "review_clear_frame",
        argNames: ["masksDir", "frameIdx"],
      );

  @override
  Future<ReviewFrame> crateApiAutomosaicReviewFrame({
    required String input,
    required String masksDir,
    required BigInt frameIdx,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          sse_encode_String(masksDir, serializer);
          sse_encode_u_64(frameIdx, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_review_frame,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAutomosaicReviewFrameConstMeta,
        argValues: [input, masksDir, frameIdx],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAutomosaicReviewFrameConstMeta =>
      const TaskConstMeta(
        debugName: "review_frame",
        argNames: ["input", "masksDir", "frameIdx"],
      );

  @override
  Future<ReviewMeta> crateApiAutomosaicReviewMeta({
    required String input,
    required String masksDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          sse_encode_String(masksDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_review_meta,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAutomosaicReviewMetaConstMeta,
        argValues: [input, masksDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAutomosaicReviewMetaConstMeta =>
      const TaskConstMeta(
        debugName: "review_meta",
        argNames: ["input", "masksDir"],
      );

  @override
  Future<SamPromptResult> crateApiAutomosaicReviewSamPrompt({
    required String input,
    required BigInt frameIdx,
    required List<double> points,
    Float32List? box,
    required String samSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          sse_encode_u_64(frameIdx, serializer);
          sse_encode_list_prim_f_32_loose(points, serializer);
          sse_encode_opt_list_prim_f_32_strict(box, serializer);
          sse_encode_String(samSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sam_prompt_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAutomosaicReviewSamPromptConstMeta,
        argValues: [input, frameIdx, points, box, samSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAutomosaicReviewSamPromptConstMeta =>
      const TaskConstMeta(
        debugName: "review_sam_prompt",
        argNames: ["input", "frameIdx", "points", "box", "samSize"],
      );

  @override
  Future<void> crateApiAutomosaicReviewSaveBrush({
    required String masksDir,
    required BigInt frameIdx,
    required bool add,
    required List<int> mask,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(masksDir, serializer);
          sse_encode_u_64(frameIdx, serializer);
          sse_encode_bool(add, serializer);
          sse_encode_list_prim_u_8_loose(mask, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAutomosaicReviewSaveBrushConstMeta,
        argValues: [masksDir, frameIdx, add, mask],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAutomosaicReviewSaveBrushConstMeta =>
      const TaskConstMeta(
        debugName: "review_save_brush",
        argNames: ["masksDir", "frameIdx", "add", "mask"],
      );

  @override
  Future<bool> crateApiAutomosaicVerifyModel({required String file}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(file, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAutomosaicVerifyModelConstMeta,
        argValues: [file],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAutomosaicVerifyModelConstMeta =>
      const TaskConstMeta(debugName: "verify_model", argNames: ["file"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<DownloadEvent> dco_decode_StreamSink_download_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<ProcessEvent> dco_decode_StreamSink_process_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ArchiveAnalyzeOptions dco_decode_archive_analyze_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ArchiveAnalyzeOptions(
      device: dco_decode_String(arr[0]),
      samSize: dco_decode_String(arr[1]),
      conf: dco_decode_f_32(arr[2]),
      tta: dco_decode_bool(arr[3]),
      hwaccel: dco_decode_String(arr[4]),
      encoder: dco_decode_String(arr[5]),
      style: dco_decode_String(arr[6]),
      strength: dco_decode_u_32(arr[7]),
      drain: dco_decode_String(arr[8]),
    );
  }

  @protected
  BackendInfo dco_decode_backend_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BackendInfo(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      available: dco_decode_bool(arr[2]),
      desc: dco_decode_String(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ArchiveAnalyzeOptions dco_decode_box_autoadd_archive_analyze_options(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_archive_analyze_options(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PresetDetail dco_decode_box_autoadd_preset_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_preset_detail(raw);
  }

  @protected
  ProcessOptions dco_decode_box_autoadd_process_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_process_options(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  DownloadEvent dco_decode_download_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return DownloadEvent_Progress(
          name: dco_decode_String(raw[1]),
          doneBytes: dco_decode_u_64(raw[2]),
          totalBytes: dco_decode_u_64(raw[3]),
        );
      case 1:
        return DownloadEvent_Finished(name: dco_decode_String(raw[1]));
      case 2:
        return DownloadEvent_Failed(error: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<BackendInfo> dco_decode_list_backend_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_backend_info).toList();
  }

  @protected
  List<ModelInfo> dco_decode_list_model_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_model_info).toList();
  }

  @protected
  List<PresetInfo> dco_decode_list_preset_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_preset_info).toList();
  }

  @protected
  List<PreviewBox> dco_decode_list_preview_box(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_preview_box).toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ReviewInstance> dco_decode_list_review_instance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_review_instance).toList();
  }

  @protected
  ModelInfo dco_decode_model_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ModelInfo(
      file: dco_decode_String(arr[0]),
      imgsz: dco_decode_u_32(arr[1]),
      sizeMb: dco_decode_f_64(arr[2]),
      present: dco_decode_bool(arr[3]),
      batchPresent: dco_decode_bool(arr[4]),
      downloadable: dco_decode_bool(arr[5]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  PresetDetail? dco_decode_opt_box_autoadd_preset_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_preset_detail(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  Float32List? dco_decode_opt_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_f_32_strict(raw);
  }

  @protected
  PresetDetail dco_decode_preset_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return PresetDetail(
      bodyModel: dco_decode_String(arr[0]),
      bodySizeMb: dco_decode_f_64(arr[1]),
      bodyBatch: dco_decode_bool(arr[2]),
      faceModel: dco_decode_opt_String(arr[3]),
      faceSizeMb: dco_decode_f_64(arr[4]),
      faceBatch: dco_decode_bool(arr[5]),
      detectEvery: dco_decode_u_32(arr[6]),
      conf: dco_decode_f_32(arr[7]),
      backendDesc: dco_decode_String(arr[8]),
    );
  }

  @protected
  PresetInfo dco_decode_preset_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return PresetInfo(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      available: dco_decode_bool(arr[2]),
      bodyModel: dco_decode_String(arr[3]),
      faceModel: dco_decode_String(arr[4]),
      conf: dco_decode_f_32(arr[5]),
      downloadable: dco_decode_bool(arr[6]),
      desc: dco_decode_String(arr[7]),
      detail: dco_decode_opt_box_autoadd_preset_detail(arr[8]),
    );
  }

  @protected
  PreviewBox dco_decode_preview_box(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return PreviewBox(
      x1: dco_decode_f_32(arr[0]),
      y1: dco_decode_f_32(arr[1]),
      x2: dco_decode_f_32(arr[2]),
      y2: dco_decode_f_32(arr[3]),
      score: dco_decode_f_32(arr[4]),
      eyes: dco_decode_opt_list_prim_f_32_strict(arr[5]),
    );
  }

  @protected
  PreviewFrame dco_decode_preview_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PreviewFrame(
      rgba: dco_decode_list_prim_u_8_strict(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      persons: dco_decode_list_preview_box(arr[3]),
      faces: dco_decode_list_preview_box(arr[4]),
    );
  }

  @protected
  ProcessEvent dco_decode_process_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ProcessEvent_StageEnter(stage: dco_decode_process_stage(raw[1]));
      case 1:
        return ProcessEvent_JobMeta(
          preset: dco_decode_String(raw[1]),
          presetLabel: dco_decode_String(raw[2]),
          bodyModel: dco_decode_String(raw[3]),
          face: dco_decode_bool(raw[4]),
          faceModel: dco_decode_opt_String(raw[5]),
          detectEvery: dco_decode_u_32(raw[6]),
          batch: dco_decode_u_32(raw[7]),
          width: dco_decode_u_32(raw[8]),
          height: dco_decode_u_32(raw[9]),
          totalFrames: dco_decode_opt_box_autoadd_u_64(raw[10]),
          modelLoadSecs: dco_decode_f_64(raw[11]),
          deviceDesc: dco_decode_String(raw[12]),
          decoder: dco_decode_String(raw[13]),
          encoder: dco_decode_String(raw[14]),
        );
      case 2:
        return ProcessEvent_Progress(
          frames: dco_decode_u_64(raw[1]),
          decoded: dco_decode_u_64(raw[2]),
          written: dco_decode_u_64(raw[3]),
          totalFrames: dco_decode_opt_box_autoadd_u_64(raw[4]),
          fps: dco_decode_f_64(raw[5]),
          etaSecs: dco_decode_opt_box_autoadd_f_64(raw[6]),
        );
      case 3:
        return ProcessEvent_Log(line: dco_decode_String(raw[1]));
      case 4:
        return ProcessEvent_PreviewPair(
          frameIdx: dco_decode_u_64(raw[1]),
          original: dco_decode_list_prim_u_8_strict(raw[2]),
          processed: dco_decode_list_prim_u_8_strict(raw[3]),
          width: dco_decode_u_32(raw[4]),
          height: dco_decode_u_32(raw[5]),
        );
      case 5:
        return ProcessEvent_Finished(
          output: dco_decode_String(raw[1]),
          frames: dco_decode_u_64(raw[2]),
          elapsedSecs: dco_decode_f_64(raw[3]),
        );
      case 6:
        return ProcessEvent_Failed(error: dco_decode_String(raw[1]));
      case 7:
        return ProcessEvent_Cancelled(frames: dco_decode_u_64(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ProcessOptions dco_decode_process_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 20)
      throw Exception('unexpected arr length: expect 20 but see ${arr.length}');
    return ProcessOptions(
      preset: dco_decode_String(arr[0]),
      conf: dco_decode_f_32(arr[1]),
      device: dco_decode_String(arr[2]),
      style: dco_decode_String(arr[3]),
      strength: dco_decode_u_32(arr[4]),
      modelPath: dco_decode_opt_String(arr[5]),
      hwaccel: dco_decode_String(arr[6]),
      encoder: dco_decode_String(arr[7]),
      bitrate: dco_decode_String(arr[8]),
      face: dco_decode_bool(arr[9]),
      faceExpand: dco_decode_u_32(arr[10]),
      detectEvery: dco_decode_u_32(arr[11]),
      faceRoi: dco_decode_u_8(arr[12]),
      track: dco_decode_bool(arr[13]),
      maskSmooth: dco_decode_bool(arr[14]),
      maskEma: dco_decode_bool(arr[15]),
      landmarkExpand: dco_decode_bool(arr[16]),
      batch: dco_decode_u_32(arr[17]),
      tta: dco_decode_u_8(arr[18]),
      gmc: dco_decode_bool(arr[19]),
    );
  }

  @protected
  ProcessStage dco_decode_process_stage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProcessStage.values[raw as int];
  }

  @protected
  ReviewFrame dco_decode_review_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ReviewFrame(
      rgba: dco_decode_list_prim_u_8_strict(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      mask: dco_decode_list_prim_u_8_strict(arr[3]),
      instances: dco_decode_list_review_instance(arr[4]),
    );
  }

  @protected
  ReviewInstance dco_decode_review_instance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ReviewInstance(
      id: dco_decode_u_64(arr[0]),
      kind: dco_decode_u_8(arr[1]),
      score: dco_decode_f_32(arr[2]),
      x1: dco_decode_f_32(arr[3]),
      y1: dco_decode_f_32(arr[4]),
      x2: dco_decode_f_32(arr[5]),
      y2: dco_decode_f_32(arr[6]),
    );
  }

  @protected
  ReviewMeta dco_decode_review_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ReviewMeta(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      frames: dco_decode_u_64(arr[2]),
      totalFrames: dco_decode_opt_box_autoadd_u_64(arr[3]),
      fps: dco_decode_f_64(arr[4]),
      patches: dco_decode_u_32(arr[5]),
    );
  }

  @protected
  SamPromptResult dco_decode_sam_prompt_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SamPromptResult(
      mask: dco_decode_list_prim_u_8_strict(arr[0]),
      iou: dco_decode_f_32(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VideoInfo dco_decode_video_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return VideoInfo(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      fps: dco_decode_f_64(arr[2]),
      codec: dco_decode_String(arr[3]),
      totalFrames: dco_decode_opt_box_autoadd_u_64(arr[4]),
      durationSecs: dco_decode_opt_box_autoadd_f_64(arr[5]),
      hasAudio: dco_decode_bool(arr[6]),
      rotation: dco_decode_f_32(arr[7]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<DownloadEvent> sse_decode_StreamSink_download_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<ProcessEvent> sse_decode_StreamSink_process_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ArchiveAnalyzeOptions sse_decode_archive_analyze_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_device = sse_decode_String(deserializer);
    var var_samSize = sse_decode_String(deserializer);
    var var_conf = sse_decode_f_32(deserializer);
    var var_tta = sse_decode_bool(deserializer);
    var var_hwaccel = sse_decode_String(deserializer);
    var var_encoder = sse_decode_String(deserializer);
    var var_style = sse_decode_String(deserializer);
    var var_strength = sse_decode_u_32(deserializer);
    var var_drain = sse_decode_String(deserializer);
    return ArchiveAnalyzeOptions(
      device: var_device,
      samSize: var_samSize,
      conf: var_conf,
      tta: var_tta,
      hwaccel: var_hwaccel,
      encoder: var_encoder,
      style: var_style,
      strength: var_strength,
      drain: var_drain,
    );
  }

  @protected
  BackendInfo sse_decode_backend_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_available = sse_decode_bool(deserializer);
    var var_desc = sse_decode_String(deserializer);
    return BackendInfo(
      id: var_id,
      label: var_label,
      available: var_available,
      desc: var_desc,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ArchiveAnalyzeOptions sse_decode_box_autoadd_archive_analyze_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_archive_analyze_options(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  PresetDetail sse_decode_box_autoadd_preset_detail(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_preset_detail(deserializer));
  }

  @protected
  ProcessOptions sse_decode_box_autoadd_process_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_process_options(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  DownloadEvent sse_decode_download_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_name = sse_decode_String(deserializer);
        var var_doneBytes = sse_decode_u_64(deserializer);
        var var_totalBytes = sse_decode_u_64(deserializer);
        return DownloadEvent_Progress(
          name: var_name,
          doneBytes: var_doneBytes,
          totalBytes: var_totalBytes,
        );
      case 1:
        var var_name = sse_decode_String(deserializer);
        return DownloadEvent_Finished(name: var_name);
      case 2:
        var var_error = sse_decode_String(deserializer);
        return DownloadEvent_Failed(error: var_error);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<BackendInfo> sse_decode_list_backend_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BackendInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_backend_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<ModelInfo> sse_decode_list_model_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ModelInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_model_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<PresetInfo> sse_decode_list_preset_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PresetInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_preset_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<PreviewBox> sse_decode_list_preview_box(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PreviewBox>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_preview_box(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ReviewInstance> sse_decode_list_review_instance(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ReviewInstance>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_review_instance(deserializer));
    }
    return ans_;
  }

  @protected
  ModelInfo sse_decode_model_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_file = sse_decode_String(deserializer);
    var var_imgsz = sse_decode_u_32(deserializer);
    var var_sizeMb = sse_decode_f_64(deserializer);
    var var_present = sse_decode_bool(deserializer);
    var var_batchPresent = sse_decode_bool(deserializer);
    var var_downloadable = sse_decode_bool(deserializer);
    return ModelInfo(
      file: var_file,
      imgsz: var_imgsz,
      sizeMb: var_sizeMb,
      present: var_present,
      batchPresent: var_batchPresent,
      downloadable: var_downloadable,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PresetDetail? sse_decode_opt_box_autoadd_preset_detail(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_preset_detail(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Float32List? sse_decode_opt_list_prim_f_32_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_f_32_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PresetDetail sse_decode_preset_detail(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bodyModel = sse_decode_String(deserializer);
    var var_bodySizeMb = sse_decode_f_64(deserializer);
    var var_bodyBatch = sse_decode_bool(deserializer);
    var var_faceModel = sse_decode_opt_String(deserializer);
    var var_faceSizeMb = sse_decode_f_64(deserializer);
    var var_faceBatch = sse_decode_bool(deserializer);
    var var_detectEvery = sse_decode_u_32(deserializer);
    var var_conf = sse_decode_f_32(deserializer);
    var var_backendDesc = sse_decode_String(deserializer);
    return PresetDetail(
      bodyModel: var_bodyModel,
      bodySizeMb: var_bodySizeMb,
      bodyBatch: var_bodyBatch,
      faceModel: var_faceModel,
      faceSizeMb: var_faceSizeMb,
      faceBatch: var_faceBatch,
      detectEvery: var_detectEvery,
      conf: var_conf,
      backendDesc: var_backendDesc,
    );
  }

  @protected
  PresetInfo sse_decode_preset_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_available = sse_decode_bool(deserializer);
    var var_bodyModel = sse_decode_String(deserializer);
    var var_faceModel = sse_decode_String(deserializer);
    var var_conf = sse_decode_f_32(deserializer);
    var var_downloadable = sse_decode_bool(deserializer);
    var var_desc = sse_decode_String(deserializer);
    var var_detail = sse_decode_opt_box_autoadd_preset_detail(deserializer);
    return PresetInfo(
      id: var_id,
      label: var_label,
      available: var_available,
      bodyModel: var_bodyModel,
      faceModel: var_faceModel,
      conf: var_conf,
      downloadable: var_downloadable,
      desc: var_desc,
      detail: var_detail,
    );
  }

  @protected
  PreviewBox sse_decode_preview_box(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x1 = sse_decode_f_32(deserializer);
    var var_y1 = sse_decode_f_32(deserializer);
    var var_x2 = sse_decode_f_32(deserializer);
    var var_y2 = sse_decode_f_32(deserializer);
    var var_score = sse_decode_f_32(deserializer);
    var var_eyes = sse_decode_opt_list_prim_f_32_strict(deserializer);
    return PreviewBox(
      x1: var_x1,
      y1: var_y1,
      x2: var_x2,
      y2: var_y2,
      score: var_score,
      eyes: var_eyes,
    );
  }

  @protected
  PreviewFrame sse_decode_preview_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rgba = sse_decode_list_prim_u_8_strict(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_persons = sse_decode_list_preview_box(deserializer);
    var var_faces = sse_decode_list_preview_box(deserializer);
    return PreviewFrame(
      rgba: var_rgba,
      width: var_width,
      height: var_height,
      persons: var_persons,
      faces: var_faces,
    );
  }

  @protected
  ProcessEvent sse_decode_process_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_stage = sse_decode_process_stage(deserializer);
        return ProcessEvent_StageEnter(stage: var_stage);
      case 1:
        var var_preset = sse_decode_String(deserializer);
        var var_presetLabel = sse_decode_String(deserializer);
        var var_bodyModel = sse_decode_String(deserializer);
        var var_face = sse_decode_bool(deserializer);
        var var_faceModel = sse_decode_opt_String(deserializer);
        var var_detectEvery = sse_decode_u_32(deserializer);
        var var_batch = sse_decode_u_32(deserializer);
        var var_width = sse_decode_u_32(deserializer);
        var var_height = sse_decode_u_32(deserializer);
        var var_totalFrames = sse_decode_opt_box_autoadd_u_64(deserializer);
        var var_modelLoadSecs = sse_decode_f_64(deserializer);
        var var_deviceDesc = sse_decode_String(deserializer);
        var var_decoder = sse_decode_String(deserializer);
        var var_encoder = sse_decode_String(deserializer);
        return ProcessEvent_JobMeta(
          preset: var_preset,
          presetLabel: var_presetLabel,
          bodyModel: var_bodyModel,
          face: var_face,
          faceModel: var_faceModel,
          detectEvery: var_detectEvery,
          batch: var_batch,
          width: var_width,
          height: var_height,
          totalFrames: var_totalFrames,
          modelLoadSecs: var_modelLoadSecs,
          deviceDesc: var_deviceDesc,
          decoder: var_decoder,
          encoder: var_encoder,
        );
      case 2:
        var var_frames = sse_decode_u_64(deserializer);
        var var_decoded = sse_decode_u_64(deserializer);
        var var_written = sse_decode_u_64(deserializer);
        var var_totalFrames = sse_decode_opt_box_autoadd_u_64(deserializer);
        var var_fps = sse_decode_f_64(deserializer);
        var var_etaSecs = sse_decode_opt_box_autoadd_f_64(deserializer);
        return ProcessEvent_Progress(
          frames: var_frames,
          decoded: var_decoded,
          written: var_written,
          totalFrames: var_totalFrames,
          fps: var_fps,
          etaSecs: var_etaSecs,
        );
      case 3:
        var var_line = sse_decode_String(deserializer);
        return ProcessEvent_Log(line: var_line);
      case 4:
        var var_frameIdx = sse_decode_u_64(deserializer);
        var var_original = sse_decode_list_prim_u_8_strict(deserializer);
        var var_processed = sse_decode_list_prim_u_8_strict(deserializer);
        var var_width = sse_decode_u_32(deserializer);
        var var_height = sse_decode_u_32(deserializer);
        return ProcessEvent_PreviewPair(
          frameIdx: var_frameIdx,
          original: var_original,
          processed: var_processed,
          width: var_width,
          height: var_height,
        );
      case 5:
        var var_output = sse_decode_String(deserializer);
        var var_frames = sse_decode_u_64(deserializer);
        var var_elapsedSecs = sse_decode_f_64(deserializer);
        return ProcessEvent_Finished(
          output: var_output,
          frames: var_frames,
          elapsedSecs: var_elapsedSecs,
        );
      case 6:
        var var_error = sse_decode_String(deserializer);
        return ProcessEvent_Failed(error: var_error);
      case 7:
        var var_frames = sse_decode_u_64(deserializer);
        return ProcessEvent_Cancelled(frames: var_frames);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ProcessOptions sse_decode_process_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_preset = sse_decode_String(deserializer);
    var var_conf = sse_decode_f_32(deserializer);
    var var_device = sse_decode_String(deserializer);
    var var_style = sse_decode_String(deserializer);
    var var_strength = sse_decode_u_32(deserializer);
    var var_modelPath = sse_decode_opt_String(deserializer);
    var var_hwaccel = sse_decode_String(deserializer);
    var var_encoder = sse_decode_String(deserializer);
    var var_bitrate = sse_decode_String(deserializer);
    var var_face = sse_decode_bool(deserializer);
    var var_faceExpand = sse_decode_u_32(deserializer);
    var var_detectEvery = sse_decode_u_32(deserializer);
    var var_faceRoi = sse_decode_u_8(deserializer);
    var var_track = sse_decode_bool(deserializer);
    var var_maskSmooth = sse_decode_bool(deserializer);
    var var_maskEma = sse_decode_bool(deserializer);
    var var_landmarkExpand = sse_decode_bool(deserializer);
    var var_batch = sse_decode_u_32(deserializer);
    var var_tta = sse_decode_u_8(deserializer);
    var var_gmc = sse_decode_bool(deserializer);
    return ProcessOptions(
      preset: var_preset,
      conf: var_conf,
      device: var_device,
      style: var_style,
      strength: var_strength,
      modelPath: var_modelPath,
      hwaccel: var_hwaccel,
      encoder: var_encoder,
      bitrate: var_bitrate,
      face: var_face,
      faceExpand: var_faceExpand,
      detectEvery: var_detectEvery,
      faceRoi: var_faceRoi,
      track: var_track,
      maskSmooth: var_maskSmooth,
      maskEma: var_maskEma,
      landmarkExpand: var_landmarkExpand,
      batch: var_batch,
      tta: var_tta,
      gmc: var_gmc,
    );
  }

  @protected
  ProcessStage sse_decode_process_stage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ProcessStage.values[inner];
  }

  @protected
  ReviewFrame sse_decode_review_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rgba = sse_decode_list_prim_u_8_strict(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_mask = sse_decode_list_prim_u_8_strict(deserializer);
    var var_instances = sse_decode_list_review_instance(deserializer);
    return ReviewFrame(
      rgba: var_rgba,
      width: var_width,
      height: var_height,
      mask: var_mask,
      instances: var_instances,
    );
  }

  @protected
  ReviewInstance sse_decode_review_instance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_kind = sse_decode_u_8(deserializer);
    var var_score = sse_decode_f_32(deserializer);
    var var_x1 = sse_decode_f_32(deserializer);
    var var_y1 = sse_decode_f_32(deserializer);
    var var_x2 = sse_decode_f_32(deserializer);
    var var_y2 = sse_decode_f_32(deserializer);
    return ReviewInstance(
      id: var_id,
      kind: var_kind,
      score: var_score,
      x1: var_x1,
      y1: var_y1,
      x2: var_x2,
      y2: var_y2,
    );
  }

  @protected
  ReviewMeta sse_decode_review_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_frames = sse_decode_u_64(deserializer);
    var var_totalFrames = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_fps = sse_decode_f_64(deserializer);
    var var_patches = sse_decode_u_32(deserializer);
    return ReviewMeta(
      width: var_width,
      height: var_height,
      frames: var_frames,
      totalFrames: var_totalFrames,
      fps: var_fps,
      patches: var_patches,
    );
  }

  @protected
  SamPromptResult sse_decode_sam_prompt_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mask = sse_decode_list_prim_u_8_strict(deserializer);
    var var_iou = sse_decode_f_32(deserializer);
    return SamPromptResult(mask: var_mask, iou: var_iou);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VideoInfo sse_decode_video_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_fps = sse_decode_f_64(deserializer);
    var var_codec = sse_decode_String(deserializer);
    var var_totalFrames = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_durationSecs = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_hasAudio = sse_decode_bool(deserializer);
    var var_rotation = sse_decode_f_32(deserializer);
    return VideoInfo(
      width: var_width,
      height: var_height,
      fps: var_fps,
      codec: var_codec,
      totalFrames: var_totalFrames,
      durationSecs: var_durationSecs,
      hasAudio: var_hasAudio,
      rotation: var_rotation,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_download_event_Sse(
    RustStreamSink<DownloadEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_download_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_process_event_Sse(
    RustStreamSink<ProcessEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_process_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_archive_analyze_options(
    ArchiveAnalyzeOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.device, serializer);
    sse_encode_String(self.samSize, serializer);
    sse_encode_f_32(self.conf, serializer);
    sse_encode_bool(self.tta, serializer);
    sse_encode_String(self.hwaccel, serializer);
    sse_encode_String(self.encoder, serializer);
    sse_encode_String(self.style, serializer);
    sse_encode_u_32(self.strength, serializer);
    sse_encode_String(self.drain, serializer);
  }

  @protected
  void sse_encode_backend_info(BackendInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_bool(self.available, serializer);
    sse_encode_String(self.desc, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_archive_analyze_options(
    ArchiveAnalyzeOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_archive_analyze_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_preset_detail(
    PresetDetail self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_preset_detail(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_process_options(
    ProcessOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_process_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_download_event(DownloadEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case DownloadEvent_Progress(
        name: final name,
        doneBytes: final doneBytes,
        totalBytes: final totalBytes,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(name, serializer);
        sse_encode_u_64(doneBytes, serializer);
        sse_encode_u_64(totalBytes, serializer);
      case DownloadEvent_Finished(name: final name):
        sse_encode_i_32(1, serializer);
        sse_encode_String(name, serializer);
      case DownloadEvent_Failed(error: final error):
        sse_encode_i_32(2, serializer);
        sse_encode_String(error, serializer);
    }
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_backend_info(
    List<BackendInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_backend_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_model_info(
    List<ModelInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_model_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_preset_info(
    List<PresetInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_preset_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_preview_box(
    List<PreviewBox> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_preview_box(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_review_instance(
    List<ReviewInstance> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_review_instance(item, serializer);
    }
  }

  @protected
  void sse_encode_model_info(ModelInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.file, serializer);
    sse_encode_u_32(self.imgsz, serializer);
    sse_encode_f_64(self.sizeMb, serializer);
    sse_encode_bool(self.present, serializer);
    sse_encode_bool(self.batchPresent, serializer);
    sse_encode_bool(self.downloadable, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_preset_detail(
    PresetDetail? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_preset_detail(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_f_32_strict(
    Float32List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_f_32_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_preset_detail(PresetDetail self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.bodyModel, serializer);
    sse_encode_f_64(self.bodySizeMb, serializer);
    sse_encode_bool(self.bodyBatch, serializer);
    sse_encode_opt_String(self.faceModel, serializer);
    sse_encode_f_64(self.faceSizeMb, serializer);
    sse_encode_bool(self.faceBatch, serializer);
    sse_encode_u_32(self.detectEvery, serializer);
    sse_encode_f_32(self.conf, serializer);
    sse_encode_String(self.backendDesc, serializer);
  }

  @protected
  void sse_encode_preset_info(PresetInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_bool(self.available, serializer);
    sse_encode_String(self.bodyModel, serializer);
    sse_encode_String(self.faceModel, serializer);
    sse_encode_f_32(self.conf, serializer);
    sse_encode_bool(self.downloadable, serializer);
    sse_encode_String(self.desc, serializer);
    sse_encode_opt_box_autoadd_preset_detail(self.detail, serializer);
  }

  @protected
  void sse_encode_preview_box(PreviewBox self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.x1, serializer);
    sse_encode_f_32(self.y1, serializer);
    sse_encode_f_32(self.x2, serializer);
    sse_encode_f_32(self.y2, serializer);
    sse_encode_f_32(self.score, serializer);
    sse_encode_opt_list_prim_f_32_strict(self.eyes, serializer);
  }

  @protected
  void sse_encode_preview_frame(PreviewFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.rgba, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_preview_box(self.persons, serializer);
    sse_encode_list_preview_box(self.faces, serializer);
  }

  @protected
  void sse_encode_process_event(ProcessEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ProcessEvent_StageEnter(stage: final stage):
        sse_encode_i_32(0, serializer);
        sse_encode_process_stage(stage, serializer);
      case ProcessEvent_JobMeta(
        preset: final preset,
        presetLabel: final presetLabel,
        bodyModel: final bodyModel,
        face: final face,
        faceModel: final faceModel,
        detectEvery: final detectEvery,
        batch: final batch,
        width: final width,
        height: final height,
        totalFrames: final totalFrames,
        modelLoadSecs: final modelLoadSecs,
        deviceDesc: final deviceDesc,
        decoder: final decoder,
        encoder: final encoder,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(preset, serializer);
        sse_encode_String(presetLabel, serializer);
        sse_encode_String(bodyModel, serializer);
        sse_encode_bool(face, serializer);
        sse_encode_opt_String(faceModel, serializer);
        sse_encode_u_32(detectEvery, serializer);
        sse_encode_u_32(batch, serializer);
        sse_encode_u_32(width, serializer);
        sse_encode_u_32(height, serializer);
        sse_encode_opt_box_autoadd_u_64(totalFrames, serializer);
        sse_encode_f_64(modelLoadSecs, serializer);
        sse_encode_String(deviceDesc, serializer);
        sse_encode_String(decoder, serializer);
        sse_encode_String(encoder, serializer);
      case ProcessEvent_Progress(
        frames: final frames,
        decoded: final decoded,
        written: final written,
        totalFrames: final totalFrames,
        fps: final fps,
        etaSecs: final etaSecs,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_u_64(frames, serializer);
        sse_encode_u_64(decoded, serializer);
        sse_encode_u_64(written, serializer);
        sse_encode_opt_box_autoadd_u_64(totalFrames, serializer);
        sse_encode_f_64(fps, serializer);
        sse_encode_opt_box_autoadd_f_64(etaSecs, serializer);
      case ProcessEvent_Log(line: final line):
        sse_encode_i_32(3, serializer);
        sse_encode_String(line, serializer);
      case ProcessEvent_PreviewPair(
        frameIdx: final frameIdx,
        original: final original,
        processed: final processed,
        width: final width,
        height: final height,
      ):
        sse_encode_i_32(4, serializer);
        sse_encode_u_64(frameIdx, serializer);
        sse_encode_list_prim_u_8_strict(original, serializer);
        sse_encode_list_prim_u_8_strict(processed, serializer);
        sse_encode_u_32(width, serializer);
        sse_encode_u_32(height, serializer);
      case ProcessEvent_Finished(
        output: final output,
        frames: final frames,
        elapsedSecs: final elapsedSecs,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_String(output, serializer);
        sse_encode_u_64(frames, serializer);
        sse_encode_f_64(elapsedSecs, serializer);
      case ProcessEvent_Failed(error: final error):
        sse_encode_i_32(6, serializer);
        sse_encode_String(error, serializer);
      case ProcessEvent_Cancelled(frames: final frames):
        sse_encode_i_32(7, serializer);
        sse_encode_u_64(frames, serializer);
    }
  }

  @protected
  void sse_encode_process_options(
    ProcessOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.preset, serializer);
    sse_encode_f_32(self.conf, serializer);
    sse_encode_String(self.device, serializer);
    sse_encode_String(self.style, serializer);
    sse_encode_u_32(self.strength, serializer);
    sse_encode_opt_String(self.modelPath, serializer);
    sse_encode_String(self.hwaccel, serializer);
    sse_encode_String(self.encoder, serializer);
    sse_encode_String(self.bitrate, serializer);
    sse_encode_bool(self.face, serializer);
    sse_encode_u_32(self.faceExpand, serializer);
    sse_encode_u_32(self.detectEvery, serializer);
    sse_encode_u_8(self.faceRoi, serializer);
    sse_encode_bool(self.track, serializer);
    sse_encode_bool(self.maskSmooth, serializer);
    sse_encode_bool(self.maskEma, serializer);
    sse_encode_bool(self.landmarkExpand, serializer);
    sse_encode_u_32(self.batch, serializer);
    sse_encode_u_8(self.tta, serializer);
    sse_encode_bool(self.gmc, serializer);
  }

  @protected
  void sse_encode_process_stage(ProcessStage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_review_frame(ReviewFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.rgba, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.mask, serializer);
    sse_encode_list_review_instance(self.instances, serializer);
  }

  @protected
  void sse_encode_review_instance(
    ReviewInstance self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_u_8(self.kind, serializer);
    sse_encode_f_32(self.score, serializer);
    sse_encode_f_32(self.x1, serializer);
    sse_encode_f_32(self.y1, serializer);
    sse_encode_f_32(self.x2, serializer);
    sse_encode_f_32(self.y2, serializer);
  }

  @protected
  void sse_encode_review_meta(ReviewMeta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_u_64(self.frames, serializer);
    sse_encode_opt_box_autoadd_u_64(self.totalFrames, serializer);
    sse_encode_f_64(self.fps, serializer);
    sse_encode_u_32(self.patches, serializer);
  }

  @protected
  void sse_encode_sam_prompt_result(
    SamPromptResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.mask, serializer);
    sse_encode_f_32(self.iou, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_video_info(VideoInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_f_64(self.fps, serializer);
    sse_encode_String(self.codec, serializer);
    sse_encode_opt_box_autoadd_u_64(self.totalFrames, serializer);
    sse_encode_opt_box_autoadd_f_64(self.durationSecs, serializer);
    sse_encode_bool(self.hasAudio, serializer);
    sse_encode_f_32(self.rotation, serializer);
  }
}
