// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'automosaic.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `batch_variant`, `cache_key`, `cancel_flag`, `effective_opts`, `load_models`, `models_cell`, `parse_style`, `preset_desc`, `resolve_encoders`, `resolve_hwaccel`, `store_models`, `take_models`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachedModels`, `Effective`, `PairSink`, `SamCache`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `emit`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `wants`

/// 推理后端清单（macOS=CoreML 计算单元四选 + CPU；其他平台=CPU）。
/// 注：trait 插件化与 tract 纯 Rust 兜底未做（§0.5-E），此 API 是其后端
/// 枚举的稳定面——后续新增后端不改 UI。
Future<List<BackendInfo>> listBackends() =>
    RustLib.instance.api.crateApiAutomosaicListBackends();

/// 五档预设列表（含可用性与描述）。archive 档可用性 = ensemble 五件套齐
/// （ReID 可选；M5 两阶段，流式 process 拒绝并指引 archiveAnalyze）。
Future<List<PresetInfo>> listPresets({required String device}) =>
    RustLib.instance.api.crateApiAutomosaicListPresets(device: device);

/// manifest 模型清单（含本地存在性；SHA 校验按需走 [`verify_model`]）。
Future<List<ModelInfo>> listModels() =>
    RustLib.instance.api.crateApiAutomosaicListModels();

/// 应用内下载模型（主文件 + 批推理伴生文件）到用户模型目录，
/// SHA256 校验 + 镜像回退；进度经事件流回报。
Stream<DownloadEvent> downloadModel({required String file}) =>
    RustLib.instance.api.crateApiAutomosaicDownloadModel(file: file);

/// 校验模型 SHA256 与 manifest 是否一致（大文件约 0.5s，按需调用）。
Future<bool> verifyModel({required String file}) =>
    RustLib.instance.api.crateApiAutomosaicVerifyModel(file: file);

Future<VideoInfo> probeVideo({required String path}) =>
    RustLib.instance.api.crateApiAutomosaicProbeVideo(path: path);

/// 取消当前处理（幂等）。
Future<void> cancelProcess() =>
    RustLib.instance.api.crateApiAutomosaicCancelProcess();

/// 处理视频：检测人体并打码。结果经事件流回报（Finished/Failed/Cancelled），
/// 返回值 Ok(()) 仅表示"已开始并结束（无论成败）"。
Stream<ProcessEvent> processVideo({
  required String input,
  required String output,
  required ProcessOptions opts,
}) => RustLib.instance.api.crateApiAutomosaicProcessVideo(
  input: input,
  output: output,
  opts: opts,
);

/// 抽取指定时间点的帧，跑完整遮罩管线（与 process_video 同一 core 检测/
/// 过滤/合成语义），返回"修改后画面"RGBA + 叠加检测框——用户在播放器
/// 任意位置所见即所得（DESIGN §7.5 预览叠加层的数据源）。
/// 单帧语义 = 管线首帧行为：track 首建即观测、EMA 首值即当前、平滑首帧透传。
Future<PreviewFrame> previewFrame({
  required String input,
  required double positionSecs,
  required double conf,
  required String device,
  required String preset,
  required String style,
  required int strength,
}) => RustLib.instance.api.crateApiAutomosaicPreviewFrame(
  input: input,
  positionSecs: positionSecs,
  conf: conf,
  device: device,
  preset: preset,
  style: style,
  strength: strength,
);

/// Archive 分析：ensemble + WBF + SAM2.1 精修 + 滑窗人脸 + masklet 关联，
/// 逐帧落盘 .mask/.inst（断点续跑：masks_dir 已有缓存则继续）。
/// 进度/完成/取消经 ProcessEvent 流（与流式 process 同协议，UI 复用处理屏）。
Stream<ProcessEvent> archiveAnalyze({
  required String input,
  required String masksDir,
  required ArchiveAnalyzeOptions opts,
}) => RustLib.instance.api.crateApiAutomosaicArchiveAnalyze(
  input: input,
  masksDir: masksDir,
  opts: opts,
);

/// Archive 渲染：读 mask 缓存 + 复核补丁，纯合成+编码（无推理）。
Stream<ProcessEvent> archiveRender({
  required String input,
  required String masksDir,
  required String output,
  required String style,
  required int strength,
  required String hwaccel,
  required String encoder,
  required String bitrate,
}) => RustLib.instance.api.crateApiAutomosaicArchiveRender(
  input: input,
  masksDir: masksDir,
  output: output,
  style: style,
  strength: strength,
  hwaccel: hwaccel,
  encoder: encoder,
  bitrate: bitrate,
);

/// 取复核帧（frame_idx 处解码原帧 + 缓存 mask + 已存补丁 + 实例层）。
Future<ReviewFrame> reviewFrame({
  required String input,
  required String masksDir,
  required BigInt frameIdx,
}) => RustLib.instance.api.crateApiAutomosaicReviewFrame(
  input: input,
  masksDir: masksDir,
  frameIdx: frameIdx,
);

/// 取复核元信息（时间轴/进度用）。
Future<ReviewMeta> reviewMeta({
  required String input,
  required String masksDir,
}) => RustLib.instance.api.crateApiAutomosaicReviewMeta(
  input: input,
  masksDir: masksDir,
);

/// 点提示 SAM 重提示（复核 UI 加/减点）：
/// `points` 为 [x, y, label]×N 扁平（label 1=前景 0=背景，全帧像素坐标），
/// 可选 `box`（[x1,y1,x2,y2]）。返回重提示 mask + IoU。
Future<SamPromptResult> reviewSamPrompt({
  required String input,
  required BigInt frameIdx,
  required List<double> points,
  Float32List? box,
  required String samSize,
}) => RustLib.instance.api.crateApiAutomosaicReviewSamPrompt(
  input: input,
  frameIdx: frameIdx,
  points: points,
  box: box,
  samSize: samSize,
);

/// 保存笔刷补丁（frame 帧的 add/erase 区域平面，W×H 0/1）。
Future<void> reviewSaveBrush({
  required String masksDir,
  required BigInt frameIdx,
  required bool add,
  required List<int> mask,
}) => RustLib.instance.api.crateApiAutomosaicReviewSaveBrush(
  masksDir: masksDir,
  frameIdx: frameIdx,
  add: add,
  mask: mask,
);

/// 撤销指定帧的全部补丁。
Future<void> reviewClearFrame({
  required String masksDir,
  required BigInt frameIdx,
}) => RustLib.instance.api.crateApiAutomosaicReviewClearFrame(
  masksDir: masksDir,
  frameIdx: frameIdx,
);

/// Archive 分析参数（复核 UI 与队列共用的入口配置）。
class ArchiveAnalyzeOptions {
  final String device;

  /// SAM2.1 规格："large"（档案级默认）/ "tiny"（调试/低配）。
  final String samSize;
  final double conf;
  final bool tta;
  final String hwaccel;
  final String encoder;

  /// 预览合成样式（mosaic/blur/solid；仅用于处理屏对照图，不影响缓存）。
  final String style;

  /// 预览合成强度。
  final int strength;

  /// 编码侧排水："null"（默认，-f null 帧即弃）/"file"（真编码探针，调试）。
  final String drain;

  const ArchiveAnalyzeOptions({
    required this.device,
    required this.samSize,
    required this.conf,
    required this.tta,
    required this.hwaccel,
    required this.encoder,
    required this.style,
    required this.strength,
    required this.drain,
  });

  @override
  int get hashCode =>
      device.hashCode ^
      samSize.hashCode ^
      conf.hashCode ^
      tta.hashCode ^
      hwaccel.hashCode ^
      encoder.hashCode ^
      style.hashCode ^
      strength.hashCode ^
      drain.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveAnalyzeOptions &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          samSize == other.samSize &&
          conf == other.conf &&
          tta == other.tta &&
          hwaccel == other.hwaccel &&
          encoder == other.encoder &&
          style == other.style &&
          strength == other.strength &&
          drain == other.drain;
}

/// 推理后端条目（DESIGN §4.3 `list_backends()`；设置屏「加速器」组数据源）。
class BackendInfo {
  /// 设备 id（与 ProcessOptions.device 同一词表）。
  final String id;

  /// 人读名。
  final String label;

  /// 本机可用（macOS 的 CoreML/CPU 恒可用；描述为配置口径——CoreML 内部
  /// 调度无法逐算子查询，与 backend_desc 的口径一致）。
  final bool available;

  /// 一行说明。
  final String desc;

  const BackendInfo({
    required this.id,
    required this.label,
    required this.available,
    required this.desc,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ available.hashCode ^ desc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackendInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          available == other.available &&
          desc == other.desc;
}

@freezed
sealed class DownloadEvent with _$DownloadEvent {
  const DownloadEvent._();

  /// name = 当前正在下载的文件名（主文件或 -b4 伴生文件）。
  const factory DownloadEvent.progress({
    required String name,
    required BigInt doneBytes,
    required BigInt totalBytes,
  }) = DownloadEvent_Progress;
  const factory DownloadEvent.finished({required String name}) =
      DownloadEvent_Finished;
  const factory DownloadEvent.failed({required String error}) =
      DownloadEvent_Failed;
}

/// manifest 模型条目状态（设置屏模型管理列表）。
class ModelInfo {
  final String file;
  final int imgsz;
  final double sizeMb;
  final bool present;
  final bool batchPresent;

  /// 缺失且 manifest 配置了下载地址 → 可在应用内下载。
  final bool downloadable;

  const ModelInfo({
    required this.file,
    required this.imgsz,
    required this.sizeMb,
    required this.present,
    required this.batchPresent,
    required this.downloadable,
  });

  @override
  int get hashCode =>
      file.hashCode ^
      imgsz.hashCode ^
      sizeMb.hashCode ^
      present.hashCode ^
      batchPresent.hashCode ^
      downloadable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelInfo &&
          runtimeType == other.runtimeType &&
          file == other.file &&
          imgsz == other.imgsz &&
          sizeMb == other.sizeMb &&
          present == other.present &&
          batchPresent == other.batchPresent &&
          downloadable == other.downloadable;
}

/// 预设就绪时的结构化明细（UI 键值展示；替代此前拼接的纯文本 desc）。
class PresetDetail {
  /// 人体模型名（去 .onnx 后缀）。
  final String bodyModel;
  final double bodySizeMb;

  /// 存在 -b4 批推理伴生模型。
  final bool bodyBatch;

  /// 人脸模型名；None = 预设未启用人脸。
  final String? faceModel;
  final double faceSizeMb;
  final bool faceBatch;

  /// 预设检测间隔（1 = 逐帧）。
  final int detectEvery;
  final double conf;

  /// 推理后端人读描述。
  final String backendDesc;

  const PresetDetail({
    required this.bodyModel,
    required this.bodySizeMb,
    required this.bodyBatch,
    this.faceModel,
    required this.faceSizeMb,
    required this.faceBatch,
    required this.detectEvery,
    required this.conf,
    required this.backendDesc,
  });

  @override
  int get hashCode =>
      bodyModel.hashCode ^
      bodySizeMb.hashCode ^
      bodyBatch.hashCode ^
      faceModel.hashCode ^
      faceSizeMb.hashCode ^
      faceBatch.hashCode ^
      detectEvery.hashCode ^
      conf.hashCode ^
      backendDesc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresetDetail &&
          runtimeType == other.runtimeType &&
          bodyModel == other.bodyModel &&
          bodySizeMb == other.bodySizeMb &&
          bodyBatch == other.bodyBatch &&
          faceModel == other.faceModel &&
          faceSizeMb == other.faceSizeMb &&
          faceBatch == other.faceBatch &&
          detectEvery == other.detectEvery &&
          conf == other.conf &&
          backendDesc == other.backendDesc;
}

/// 预设可用性与描述（ConfigScreen 预设选择器 + 模型卡片数据源）。
class PresetInfo {
  final String id;
  final String label;

  /// 人体模型是否就绪
  final bool available;
  final String bodyModel;
  final String faceModel;

  /// 预设默认置信度（切预设时 UI 联动滑杆）
  final double conf;

  /// 模型缺失但可在应用内下载（manifest 配置了 URL）
  final bool downloadable;

  /// 模型缺失/未实现时的指引文本；可用时为空（明细走 detail）。
  final String desc;

  /// 预设就绪时的结构化明细（available 时 Some）。
  final PresetDetail? detail;

  const PresetInfo({
    required this.id,
    required this.label,
    required this.available,
    required this.bodyModel,
    required this.faceModel,
    required this.conf,
    required this.downloadable,
    required this.desc,
    this.detail,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      available.hashCode ^
      bodyModel.hashCode ^
      faceModel.hashCode ^
      conf.hashCode ^
      downloadable.hashCode ^
      desc.hashCode ^
      detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresetInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          available == other.available &&
          bodyModel == other.bodyModel &&
          faceModel == other.faceModel &&
          conf == other.conf &&
          downloadable == other.downloadable &&
          desc == other.desc &&
          detail == other.detail;
}

/// 叠加框（原始分辨率像素坐标；eyes = [lx,ly,rx,ry]，无 landmark 为 None）。
class PreviewBox {
  final double x1;
  final double y1;
  final double x2;
  final double y2;
  final double score;
  final Float32List? eyes;

  const PreviewBox({
    required this.x1,
    required this.y1,
    required this.x2,
    required this.y2,
    required this.score,
    this.eyes,
  });

  @override
  int get hashCode =>
      x1.hashCode ^
      y1.hashCode ^
      x2.hashCode ^
      y2.hashCode ^
      score.hashCode ^
      eyes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreviewBox &&
          runtimeType == other.runtimeType &&
          x1 == other.x1 &&
          y1 == other.y1 &&
          x2 == other.x2 &&
          y2 == other.y2 &&
          score == other.score &&
          eyes == other.eyes;
}

/// 预览帧：应用真实遮罩样式后的 RGBA（"修改后画面"）+ 叠加检测框
/// （DESIGN §7.5：CustomPainter 画 person 框/人脸框/双眼点）。
class PreviewFrame {
  final Uint8List rgba;
  final int width;
  final int height;

  /// person 检测框（原始分辨率坐标）。
  final List<PreviewBox> persons;

  /// 人脸框（含双眼 landmark，像素坐标）。
  final List<PreviewBox> faces;

  const PreviewFrame({
    required this.rgba,
    required this.width,
    required this.height,
    required this.persons,
    required this.faces,
  });

  @override
  int get hashCode =>
      rgba.hashCode ^
      width.hashCode ^
      height.hashCode ^
      persons.hashCode ^
      faces.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreviewFrame &&
          runtimeType == other.runtimeType &&
          rgba == other.rgba &&
          width == other.width &&
          height == other.height &&
          persons == other.persons &&
          faces == other.faces;
}

@freezed
sealed class ProcessEvent with _$ProcessEvent {
  const ProcessEvent._();

  /// 任务级阶段切换（结构化状态机事件，UI 阶段行数据源）。
  const factory ProcessEvent.stageEnter({required ProcessStage stage}) =
      ProcessEvent_StageEnter;

  /// 任务元数据（结构化，处理屏任务卡"任务信息"数据源；替代此前的
  /// 两条纯文本日志——预设/模型/后端/分辨率等以键值展示而非管道符文本）。
  const factory ProcessEvent.jobMeta({
    /// 预设 id（speed/balanced/accurate/extreme）。
    required String preset,

    /// 预设人读名（速度/均衡/准确/极致）。
    required String presetLabel,

    /// 人体模型文件名。
    required String bodyModel,

    /// 是否启用人脸检测。
    required bool face,

    /// 人脸模型文件名（未启用为 None）。
    String? faceModel,

    /// 隔帧检测间隔（1 = 逐帧）。
    required int detectEvery,

    /// 批推理大小。
    required int batch,
    required int width,
    required int height,
    BigInt? totalFrames,

    /// 模型加载耗时（秒；CoreML 编译有持久缓存时 <1s）。
    required double modelLoadSecs,

    /// 推理后端人读描述（backend_desc）。
    required String deviceDesc,

    /// 实际使用的解码 hwaccel（None = 软件解码）。
    required String decoder,

    /// 本次尝试的编码器（编码器回退重试时随重发更新）。
    required String encoder,
  }) = ProcessEvent_JobMeta;
  const factory ProcessEvent.progress({
    required BigInt frames,
    required BigInt decoded,
    required BigInt written,
    BigInt? totalFrames,
    required double fps,
    double? etaSecs,
  }) = ProcessEvent_Progress;

  /// 关键节点日志（模型加载/编码器回退/完成等，日志面板展示）。
  const factory ProcessEvent.log({required String line}) = ProcessEvent_Log;

  /// 处理中的左右对照预览（缩放后的 RGBA，每 8 帧一对）。
  const factory ProcessEvent.previewPair({
    required BigInt frameIdx,
    required Uint8List original,
    required Uint8List processed,
    required int width,
    required int height,
  }) = ProcessEvent_PreviewPair;
  const factory ProcessEvent.finished({
    required String output,
    required BigInt frames,
    required double elapsedSecs,
  }) = ProcessEvent_Finished;
  const factory ProcessEvent.failed({required String error}) =
      ProcessEvent_Failed;
  const factory ProcessEvent.cancelled({required BigInt frames}) =
      ProcessEvent_Cancelled;
}

class ProcessOptions {
  /// 质量预设 id：speed / balanced / accurate / extreme
  final String preset;
  final double conf;

  /// auto（macOS=CoreML）/ cpu
  final String device;

  /// mosaic / blur / solid
  final String style;
  final int strength;

  /// 显式人体模型（自导入 ONNX）；None = 用预设模型
  final String? modelPath;

  /// auto / none / 显式名
  final String hwaccel;

  /// auto / 显式名
  final String encoder;

  /// 目标码率；"auto" = 按分辨率档位缩放（1080p 基准 6M，core 侧解析）
  final String bitrate;

  /// 是否启用人脸检测
  final bool face;

  /// 人脸框外扩像素；0 = 取预设默认
  final int faceExpand;

  /// 隔帧检测间隔覆写；0 = 取预设默认
  final int detectEvery;

  /// 人脸级联 ROI 三态：0 = 跟随预设（极致档开），1 = 强制开，2 = 强制关
  /// （俯视视角建议关：头部区域假设失效时 ROI 会引入误检）
  final int faceRoi;

  /// ByteTrack 跟踪（含 Kalman 预测/低分救援/漏检保持）
  final bool track;

  /// mask 时序平滑（上一帧膨胀并集）
  final bool maskSmooth;

  /// per-ID mask EMA（α=0.7）
  final bool maskEma;

  /// landmark 外扩（眼距自适应抗转头）
  final bool landmarkExpand;

  /// 批推理大小覆写；0 = 取预设默认
  final int batch;

  /// 翻转 TTA 三态：0 = 跟随预设（极致档开），1 = 强制开，2 = 强制关
  /// （推理 ×2 换召回，离线档推荐）
  final int tta;

  /// 相位相关全局运动补偿（运动镜头：预测框平移 + 保持帧遮罩跟随；静机位自动零位移）
  final bool gmc;

  const ProcessOptions({
    required this.preset,
    required this.conf,
    required this.device,
    required this.style,
    required this.strength,
    this.modelPath,
    required this.hwaccel,
    required this.encoder,
    required this.bitrate,
    required this.face,
    required this.faceExpand,
    required this.detectEvery,
    required this.faceRoi,
    required this.track,
    required this.maskSmooth,
    required this.maskEma,
    required this.landmarkExpand,
    required this.batch,
    required this.tta,
    required this.gmc,
  });

  @override
  int get hashCode =>
      preset.hashCode ^
      conf.hashCode ^
      device.hashCode ^
      style.hashCode ^
      strength.hashCode ^
      modelPath.hashCode ^
      hwaccel.hashCode ^
      encoder.hashCode ^
      bitrate.hashCode ^
      face.hashCode ^
      faceExpand.hashCode ^
      detectEvery.hashCode ^
      faceRoi.hashCode ^
      track.hashCode ^
      maskSmooth.hashCode ^
      maskEma.hashCode ^
      landmarkExpand.hashCode ^
      batch.hashCode ^
      tta.hashCode ^
      gmc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessOptions &&
          runtimeType == other.runtimeType &&
          preset == other.preset &&
          conf == other.conf &&
          device == other.device &&
          style == other.style &&
          strength == other.strength &&
          modelPath == other.modelPath &&
          hwaccel == other.hwaccel &&
          encoder == other.encoder &&
          bitrate == other.bitrate &&
          face == other.face &&
          faceExpand == other.faceExpand &&
          detectEvery == other.detectEvery &&
          faceRoi == other.faceRoi &&
          track == other.track &&
          maskSmooth == other.maskSmooth &&
          maskEma == other.maskEma &&
          landmarkExpand == other.landmarkExpand &&
          batch == other.batch &&
          tta == other.tta &&
          gmc == other.gmc;
}

/// 处理阶段（DESIGN §7.4 Stage 的流式管线子集：流式模式下各段并发，
/// 事件标记任务级状态机边界而非独占段）。
enum ProcessStage {
  /// 探测视频元数据（分辨率/音轨/旋转）。
  probing,

  /// 模型就绪，推理+合成+编码管线启动。
  inferring,

  /// 帧流结束，编码器收尾写 moov（faststart 二次排布）。
  finalizing,
}

/// 复核帧：原帧缩放 RGBA + 生效 mask（含补丁）平面 + 实例框列表。
class ReviewFrame {
  final Uint8List rgba;
  final int width;
  final int height;

  /// W×H，1=遮罩（缓存 mask + 补丁后）。
  final Uint8List mask;

  /// 该帧的 masklet 实例（id/kind/score/框）。
  final List<ReviewInstance> instances;

  const ReviewFrame({
    required this.rgba,
    required this.width,
    required this.height,
    required this.mask,
    required this.instances,
  });

  @override
  int get hashCode =>
      rgba.hashCode ^
      width.hashCode ^
      height.hashCode ^
      mask.hashCode ^
      instances.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewFrame &&
          runtimeType == other.runtimeType &&
          rgba == other.rgba &&
          width == other.width &&
          height == other.height &&
          mask == other.mask &&
          instances == other.instances;
}

/// 复核实例条目。
class ReviewInstance {
  final BigInt id;

  /// 0=person，1=孤立人脸。
  final int kind;
  final double score;
  final double x1;
  final double y1;
  final double x2;
  final double y2;

  const ReviewInstance({
    required this.id,
    required this.kind,
    required this.score,
    required this.x1,
    required this.y1,
    required this.x2,
    required this.y2,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      score.hashCode ^
      x1.hashCode ^
      y1.hashCode ^
      x2.hashCode ^
      y2.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewInstance &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          score == other.score &&
          x1 == other.x1 &&
          y1 == other.y1 &&
          x2 == other.x2 &&
          y2 == other.y2;
}

/// 复核缓存元信息。
class ReviewMeta {
  final int width;
  final int height;

  /// 已分析帧数（断点续跑进度/时间轴范围）。
  final BigInt frames;

  /// 视频总帧数。
  final BigInt? totalFrames;
  final double fps;

  /// 已存补丁条数。
  final int patches;

  const ReviewMeta({
    required this.width,
    required this.height,
    required this.frames,
    this.totalFrames,
    required this.fps,
    required this.patches,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      frames.hashCode ^
      totalFrames.hashCode ^
      fps.hashCode ^
      patches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewMeta &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          frames == other.frames &&
          totalFrames == other.totalFrames &&
          fps == other.fps &&
          patches == other.patches;
}

/// SAM 重提示结果。
class SamPromptResult {
  final Uint8List mask;
  final double iou;

  const SamPromptResult({required this.mask, required this.iou});

  @override
  int get hashCode => mask.hashCode ^ iou.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SamPromptResult &&
          runtimeType == other.runtimeType &&
          mask == other.mask &&
          iou == other.iou;
}

class VideoInfo {
  final int width;
  final int height;
  final double fps;
  final String codec;
  final BigInt? totalFrames;
  final double? durationSecs;
  final bool hasAudio;

  /// 容器旋转元数据（度；±90 时 width/height 已是旋转后的显示尺寸）
  final double rotation;

  const VideoInfo({
    required this.width,
    required this.height,
    required this.fps,
    required this.codec,
    this.totalFrames,
    this.durationSecs,
    required this.hasAudio,
    required this.rotation,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      fps.hashCode ^
      codec.hashCode ^
      totalFrames.hashCode ^
      durationSecs.hashCode ^
      hasAudio.hashCode ^
      rotation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          fps == other.fps &&
          codec == other.codec &&
          totalFrames == other.totalFrames &&
          durationSecs == other.durationSecs &&
          hasAudio == other.hasAudio &&
          rotation == other.rotation;
}
